# Generated by Django 2.0.7 on 2018-07-26 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_authorinstance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorinstance',
            name='book',
        ),
        migrations.RemoveField(
            model_name='authorinstance',
            name='borrower',
        ),
        migrations.DeleteModel(
            name='AuthorInstance',
        ),
    ]
